### ISSUE TITLE
Fixer l'entête de l'export

### ISSUE THREAD

**Issue by loicberbey** [tprouvot/Chrome-Salesforce-inspector#10]
Pour plus de lisibilité sur l'instant, avant même la copie dans un fichier excel. C'est toujours plus pratique d'avoir l'entête visible durant le scroll. 

![image](https://user-images.githubusercontent.com/4833042/143839512-bcd0d45e-f6c1-4599-9f51-955ebeee03c7.png)

Solution dégradée : insérer des lignes d'entête toutes les X lignes qui ne seront évidemment pas à prendre en compte dans l'export.

**Comment by tprouvot** [comment]
@loicberbey done
#15
