### ISSUE TITLE
Harmoniser les entêtes

### ISSUE THREAD

**Issue by lberbey** [tprouvot/Chrome-Salesforce-inspector#11]
Un petit gain de place pour visualiser un peu plus de lignes.

![image](https://user-images.githubusercontent.com/4833042/143841502-2c7ebea9-09e2-40b8-8e69-f7f8ea50d774.png)

**Comment by tprouvot** [comment]
Finally ! 
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/35368290/220069532-17578be5-b0d5-4adf-9ce2-95099c86c909.png">
