### ISSUE TITLE
[data-import] Auto Fill object on import

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Chrome-Salesforce-inspector#30]
**Is your feature request related to a problem? Please describe.**
When importing data it would be great if the SObject could be set automatically.

**Additional context**
Based on the issue https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/issues/242

**Comment by tprouvot** [comment]
Instead of getting the SObject based on the id, we get the information from the header:
https://github.com/tprouvot/Chrome-Salesforce-inspector/pull/31

**Comment by RebbePod** [comment]
Thank you works well.
Is there any way to get it based on the ID for instances when there is no header?
For cases where not exporting from inspector and there isn't the object headers "[Account]"
