### ISSUE TITLE
Scrolling issue in flow screen

### ISSUE THREAD

**Issue by CamilleGuillory** [tprouvot/Chrome-Salesforce-inspector#54]
When moving the flow with "left click + drag" from the top of the flow and then scrolling with the mouse wheel, we cannot go back to the top. 
The scrollbar is getting "bigger" when "left click + drag"  from the top. It shouldn't be the case.

![Sans titre](https://user-images.githubusercontent.com/45099363/231119079-3e40d0aa-d6a8-4fae-8f34-5ff354d8ca03.gif)

**Comment by tprouvot** [comment]
@CamilleGuillory I tested the behaviour you mentioned and I can reproduce it. 
But once on the top I can move up with left click and drag, which finally cancel my first manual move.
Have you tried this ?


![2023-04-11_21-46-44 (1)](https://user-images.githubusercontent.com/35368290/231273321-4b6c202d-77fa-483f-8bf1-8171118004ae.gif)

**Comment by tprouvot** [comment]
Hi @CamilleGuillory,
Ad discussed together earlier I think this is normal behaviour since a manual move was made on the page.
The top of the page is still available when moving traditionally in the flow
